version: '3'
services:
  monolithe:
    build:
      context: ./springboot/monolithique
    image: monolithe:latest
    ports:
      - "5105:5105"

  nginx-setup:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/var/tmp/nginx.conf
    command: cp /var/tmp/nginx.conf /etc/nginx/nginx.conf

  nginx-container:
    image: nginx:latest
    network_mode: "host"
    volumes:
      - /var/tmp/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nginx-setup

  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: "false"
      ACTIVEMQ_USERNAME: myuser
      ACTIVEMQ_PASSWORD: mypwd
      ACTIVEMQ_WEBADMIN_USERNAME: myuserweb
      ACTIVEMQ_WEBADMIN_PASSWORD: mypwd
