version: '3'

services:
  monolithe:
    build:
      context: ./springboot/monolithique
    image: monolithe:latest
    ports:
      - "5105:5105"

  nginx:
    image: nginx:latest
    ports:
      - "5100:5100"
    volumes:
      - /var/tmp/nginx.conf:/etc/nginx/nginx.conf:ro

  activemq:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: "false"
      ACTIVEMQ_USERNAME: myuser
      ACTIVEMQ_PASSWORD: mypwd
      ACTIVEMQ_WEBADMIN_USERNAME: myuserweb
      ACTIVEMQ_WEBADMIN_PASSWORD: mypwd
